# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bnort\work\ImageJ2022\tnia\tnia-python\tnia\gui\deconvolution\richardson_lucy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(137, 71)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 131, 67))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_iterations = QtWidgets.QLabel(self.layoutWidget)
        self.label_iterations.setObjectName("label_iterations")
        self.gridLayout.addWidget(self.label_iterations, 0, 0, 1, 1)
        self.doubleSpinBox_regularization = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_regularization.setDecimals(4)
        self.doubleSpinBox_regularization.setMaximum(1.0)
        self.doubleSpinBox_regularization.setSingleStep(0.0001)
        self.doubleSpinBox_regularization.setProperty("value", 0.0001)
        self.doubleSpinBox_regularization.setObjectName("doubleSpinBox_regularization")
        self.gridLayout.addWidget(self.doubleSpinBox_regularization, 1, 1, 1, 1)
        self.spinBox_iterations = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_iterations.setMinimum(1)
        self.spinBox_iterations.setMaximum(10000)
        self.spinBox_iterations.setSingleStep(100)
        self.spinBox_iterations.setProperty("value", 100)
        self.spinBox_iterations.setObjectName("spinBox_iterations")
        self.gridLayout.addWidget(self.spinBox_iterations, 0, 1, 1, 1)
        self.label_regularization = QtWidgets.QLabel(self.layoutWidget)
        self.label_regularization.setObjectName("label_regularization")
        self.gridLayout.addWidget(self.label_regularization, 1, 0, 1, 1)
        self.label_ = QtWidgets.QLabel(self.layoutWidget)
        self.label_.setObjectName("label_")
        self.gridLayout.addWidget(self.label_, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_iterations.setText(_translate("Form", "Iterations:"))
        self.label_regularization.setText(_translate("Form", "Regularization"))
        self.label_.setText(_translate("Form", "TextLabel"))
